name: Deploy to EC2 with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SECRET_KEYS }}

    - name: Deploy HTML to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./index.html ${{ secrets.SECRET_USER }}@${{ secrets.SECRET_HOST }}:/tmp/
        ssh -o StrictHostKeyChecking=no ${{ secrets.SECRET_USER }}@${{ secrets.SECRET_HOST }} "sudo mv /tmp/index.html /var/www/html/ && sudo systemctl restart nginx"